version: '3.7'


services:
  tg_bot:
    image: ai_assistant_template_tg_bot:latest
    build:
      context: .
      dockerfile: Dockerfile
    deploy:
      replicas: 1
      restart_policy:
        condition: any
      placement:
        constraints:
          - node.role == manager
      resources:
        limits:
          cpus: '0.5'
          memory: '512M'
    volumes:
      - ./logs:/app/logs
    networks:
      - network
    environment:
      - URL_TO_API=${URL_TO_API}
      - ADMIN_ID=${ADMIN_ID}
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - ACCESS_TOKEN=${ACCESS_TOKEN}
      - UNI_ID=${UNI_ID}


networks:
  network:
    driver: overlay