version: '3.7'

x-common-environment: &common-environment
  URL_TO_API: 
  ADMIN_ID:

services:
  your_uni:
    image: ai_assistant_template_tg_bot:latest
    deploy:
      replicas: 1
      restart_policy:
        condition: any
      placement:
        constraints:
          - node.role == manager
      resources:
        limits:
          cpus: '0.5'
          memory: '512M'
    volumes:
      - ./logs:/app/logs
    networks:
      - network
    environment:
      <<: *common-environment
      TELEGRAM_BOT_TOKEN:
      ACCESS_TOKEN: 
      UNI_ID:


networks:
  network:
    driver: overlay